# Generated by Django 2.1.5 on 2019-01-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190105_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
