# Generated by Django 2.1.5 on 2019-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190105_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Phone Number'),
        ),
    ]
